name: "Setup Virtual Env"
runs:
  using: composite
  steps:
  - name: Install Dependencies
    shell: bash
    #working-directory: $HOME
    run: |
      python -m venv ~/venv
      ls ~
      realpath ~
      # BASH_ENV does not exist outdife of circleci.
      # the goal is to source the venv in future jobs,
      # so add it as a script to /etc/profile.d
      echo "echo AAA; . ~/venv/bin/activate" >> $GITHUB_ENV
      #echo "echo AAA; . ~/venv/bin/activate" > detectron2_activate_venv.sh
      #sudo mv detectron2_activate_venv.sh /etc/profile.d/
      . ~/venv/bin/activate
      python --version
      which python
      which pip
      pip install --upgrade pip
